// <auto-generated />
using System;
using Boleiroffice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Boleiroffice.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706153356_AddRachaoEvento")]
    partial class AddRachaoEvento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Boleiroffice.Domain.Entities.AvaliacaoQuadra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comentario")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuadraId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("QuadraId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("avaliacoes_quadra", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ComentarioFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DataComentario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId")
                        .HasDatabaseName("IX_ComentarioFeed_DesafioId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("comentarios_feed", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ConfirmacaoPresenca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.HasIndex("JogadorId", "DesafioId")
                        .IsUnique();

                    b.ToTable("confirmacoes_presenca", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Desafio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("DataAceite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataJogo")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataPropostaResultado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResultadoConfirmadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("HoraJogo")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarCriador")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarCriadorProposto")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarDesafiante")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarDesafianteProposto")
                        .HasColumnType("integer");

                    b.Property<bool>("ResultadoConfirmadoPeloCriador")
                        .HasColumnType("boolean");

                    b.Property<bool>("ResultadoConfirmadoPeloDesafiante")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ResultadoPropostoPorTimeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("TimeCriadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeDesafianteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Bairro")
                        .HasDatabaseName("IX_Desafio_Bairro");

                    b.HasIndex("DataJogo")
                        .HasDatabaseName("IX_Desafio_DataJogo");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Desafio_Status");

                    b.HasIndex("TimeCriadorId");

                    b.HasIndex("TimeDesafianteId");

                    b.ToTable("desafios", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.DisponibilidadeTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("EnderecoCompleto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<TimeOnly>("Horario")
                        .HasColumnType("time without time zone");

                    b.Property<string>("NomeLocal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId", "DiaSemana", "Horario")
                        .IsUnique();

                    b.ToTable("disponibilidades_time", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.FinanceiroItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.ToTable("financeiro_itens", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.GolAmistoso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssistenteNome")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AutorNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PartidaAmistosoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeNumero")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_GolAmistoso_EmpresaId");

                    b.HasIndex("PartidaAmistosoId")
                        .HasDatabaseName("IX_GolAmistoso_PartidaId");

                    b.ToTable("gols_amistoso", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.GolPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("QuantidadeGols")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId")
                        .HasDatabaseName("IX_GolPartida_DesafioId");

                    b.HasIndex("TimeId")
                        .HasDatabaseName("IX_GolPartida_TimeId");

                    b.ToTable("gols_partida", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("integer");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId")
                        .HasDatabaseName("IX_Jogador_TimeId");

                    b.HasIndex("TimeId", "NumeroCamisa")
                        .IsUnique();

                    b.ToTable("jogadores", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.JogadorAmistoso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("PagouMensalidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_JogadorAmistoso_EmpresaId");

                    b.ToTable("jogadores_amistoso", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.MensagemDesafio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId")
                        .HasDatabaseName("IX_MensagemDesafio_DesafioId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("mensagens_desafio", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .HasColumnType("boolean");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Lida")
                        .HasDatabaseName("IX_Notificacao_Empresa_Lida");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PartidaAmistoso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Finalizada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Time1Gols")
                        .HasColumnType("integer");

                    b.Property<string>("Time1Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Time2Gols")
                        .HasColumnType("integer");

                    b.Property<string>("Time2Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Finalizada")
                        .HasDatabaseName("IX_PartidaAmistoso_Empresa_Finalizada");

                    b.ToTable("partidas_amistoso", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PartidaTorneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DataJogo")
                        .HasColumnType("date");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<TimeOnly?>("HoraJogo")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PlacarMandante")
                        .HasColumnType("integer");

                    b.Property<int?>("PlacarVisitante")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TimeMandanteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeVisitanteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeMandanteId");

                    b.HasIndex("TimeVisitanteId");

                    b.HasIndex("TorneioId");

                    b.ToTable("partidas_torneio", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PostMural", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeAutor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_PostMural_EmpresaId");

                    b.ToTable("posts_mural", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Quadra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Iluminacao")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TipoGrama")
                        .HasColumnType("integer");

                    b.Property<bool>("Vestiario")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Bairro")
                        .HasDatabaseName("IX_Quadra_Bairro");

                    b.ToTable("quadras", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.RachaoConfirmacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RachaoEventoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RachaoEventoId")
                        .HasDatabaseName("IX_RachaoConfirmacao_EventoId");

                    b.ToTable("rachao_confirmacoes", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.RachaoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("HorarioEvento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroTimes")
                        .HasColumnType("integer");

                    b.Property<bool>("SorteioFeito")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_RachaoEvento_EmpresaId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RachaoEvento_Token");

                    b.ToTable("rachao_eventos", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ReacaoFeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("DesafioId", "EmpresaId")
                        .IsUnique();

                    b.ToTable("reacoes_feed", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Temporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("temporadas", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BairroBase")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("BloqueioAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("CorPrimaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorSecundaria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<int>("EscudoShape")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PenalidadesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_Time_EmpresaId");

                    b.ToTable("times", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TimeAmistoso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("IX_TimeAmistoso_EmpresaId");

                    b.ToTable("times_amistoso", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TimeAmistosoJogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JogadorAmistosoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TimeAmistosoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeAmistosoId")
                        .HasDatabaseName("IX_TimeAmistosoJogador_TimeId");

                    b.ToTable("times_amistoso_jogadores", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Torneio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmpresaOrganizadoraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Formato")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaOrganizadoraId");

                    b.ToTable("torneios", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TorneioInscricao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GrupoLetra")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TorneioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeId");

                    b.HasIndex("TorneioId", "TimeId")
                        .IsUnique();

                    b.ToTable("torneio_inscricoes", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.VotoMvp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataVoto")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JogadorVotadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotantePorEmpresaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JogadorVotadoId");

                    b.HasIndex("VotantePorEmpresaId");

                    b.HasIndex("DesafioId", "VotantePorEmpresaId")
                        .IsUnique();

                    b.ToTable("votos_mvp", (string)null);
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.AvaliacaoQuadra", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Quadra", "Quadra")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("QuadraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Quadra");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ComentarioFeed", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ConfirmacaoPresenca", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany("ConfirmacoesPresenca")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Jogador", "Jogador")
                        .WithMany("ConfirmacoesPresenca")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Desafio", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "TimeCriador")
                        .WithMany("DesafiosCriados")
                        .HasForeignKey("TimeCriadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Time", "TimeDesafiante")
                        .WithMany("DesafiosRecebidos")
                        .HasForeignKey("TimeDesafianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TimeCriador");

                    b.Navigation("TimeDesafiante");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.DisponibilidadeTime", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.FinanceiroItem", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.GolAmistoso", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.PartidaAmistoso", "Partida")
                        .WithMany("Gols")
                        .HasForeignKey("PartidaAmistosoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.GolPartida", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany("Gols")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Time", "Time")
                        .WithMany("GolsMarcados")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Jogador", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.JogadorAmistoso", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.MensagemDesafio", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PartidaAmistoso", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PartidaTorneio", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "TimeMandante")
                        .WithMany()
                        .HasForeignKey("TimeMandanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Time", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Boleiroffice.Domain.Entities.Torneio", "Torneio")
                        .WithMany("Partidas")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeMandante");

                    b.Navigation("TimeVisitante");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PostMural", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.RachaoConfirmacao", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.RachaoEvento", "Evento")
                        .WithMany("Confirmacoes")
                        .HasForeignKey("RachaoEventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.RachaoEvento", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.ReacaoFeed", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Time", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Times")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TimeAmistoso", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TimeAmistosoJogador", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.TimeAmistoso", "TimeAmistoso")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeAmistosoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeAmistoso");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Torneio", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "EmpresaOrganizadora")
                        .WithMany()
                        .HasForeignKey("EmpresaOrganizadoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmpresaOrganizadora");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TorneioInscricao", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Time", "Time")
                        .WithMany()
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Torneio", "Torneio")
                        .WithMany("Inscricoes")
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Time");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.VotoMvp", b =>
                {
                    b.HasOne("Boleiroffice.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Jogador", "JogadorVotado")
                        .WithMany()
                        .HasForeignKey("JogadorVotadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Boleiroffice.Domain.Entities.Empresa", "VotantePorEmpresa")
                        .WithMany()
                        .HasForeignKey("VotantePorEmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("JogadorVotado");

                    b.Navigation("VotantePorEmpresa");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Desafio", b =>
                {
                    b.Navigation("ConfirmacoesPresenca");

                    b.Navigation("Gols");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Times");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Jogador", b =>
                {
                    b.Navigation("ConfirmacoesPresenca");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.PartidaAmistoso", b =>
                {
                    b.Navigation("Gols");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Quadra", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.RachaoEvento", b =>
                {
                    b.Navigation("Confirmacoes");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Time", b =>
                {
                    b.Navigation("DesafiosCriados");

                    b.Navigation("DesafiosRecebidos");

                    b.Navigation("GolsMarcados");

                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.TimeAmistoso", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Boleiroffice.Domain.Entities.Torneio", b =>
                {
                    b.Navigation("Inscricoes");

                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
